Merge pull request #1810 from FCP-INDI/pin/AFNI
📌 Pin AFNI version for standard, lite, and ABCD variant images

diff --git a/.github/workflows/build_stages.yml b/.github/workflows/build_stages.yml
--- a/.github/workflows/build_stages.yml
+++ b/.github/workflows/build_stages.yml
@@ -46,14 +46,14 @@ jobs:
         with:
           fetch-depth: 2
       - name: Get changed files since fork point
-        uses: tj-actions/changed-files@v17.2
+        uses: tj-actions/changed-files@v34.0.0
         if: github.event.inputs.base_ref != ''
         id: changed-files-base
         with:
           use_fork_point: "true"
           files: .github/Dockerfiles/*
       - name: Get changed files since last commit
-        uses: tj-actions/changed-files@v17.2
+        uses: tj-actions/changed-files@v34.0.0
         if: github.event.inputs.base_ref == ''
         id: changed-files
         with:
@@ -68,7 +68,7 @@ jobs:
           docker manifest inspect $DOCKER_TAG >/dev/null
           echo "not_yet_exists=$?" >> $GITHUB_OUTPUT
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1.6.0
+        uses: docker/setup-buildx-action@v2.2.1
         if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
@@ -78,14 +78,14 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
         if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
       - name: Build and push Docker image
-        uses: docker/build-push-action@v2.9.0
+        uses: docker/build-push-action@v3.2.0
         with:
           file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
           push: true
           tags: |
             ${{ env.DOCKER_TAG }}
           cache-from: type=gha
-          cache-to: type=gha,mode=max
+          cache-to: type=gha,mode=min
         if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
   
   stages:
@@ -95,13 +95,11 @@ jobs:
       matrix:
         Dockerfile:
         - AFNI.16.2.07.neurodocker-xenial
-        - AFNI.20.0.04-bionic
+        - AFNI.21.2.06-bionic
         - ANTs.2.2.0.neurodocker-bionic
         - c3d.1.0.0-xenial
         - connectome-workbench.1.3.2-1.neurodebian-bionic
         - connectome-workbench.1.3.2-2.neurodebian-xenial
-        - FreeSurfer.6.0.0-min.neurodocker-bionic
-        - FreeSurfer.6.0.1-min-xenial
         - FSL.5.0.9-5.neurodebian-xenial
         - FSL.5.0.10-bionic
         - ICA-AROMA.0.4.5-xenial
@@ -119,36 +117,40 @@ jobs:
         with:
           fetch-depth: 2
       - name: Get changed files since fork point
-        uses: tj-actions/changed-files@v17.2
+        uses: tj-actions/changed-files@v34.0.0
         if: github.event.inputs.base_ref != ''
         id: changed-files-base
         with:
           use_fork_point: "true"
-          files: .github/Dockerfiles/*
+          files: |
+            dev/docker_data/required_afni_pkgs.txt
+            .github/Dockerfiles/*
       - name: Get changed files since last commit
-        uses: tj-actions/changed-files@v17.2
+        uses: tj-actions/changed-files@v34.0.0
         if: github.event.inputs.base_ref == ''
         id: changed-files
         with:
           since_last_remote_commit: "true"
-          files: .github/Dockerfiles/*
+          files: |
+            dev/docker_data/required_afni_pkgs.txt
+            .github/Dockerfiles/*
       - name: Clear up some space on runner
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
         run: |
           sudo rm -rf /usr/share/dotnet
           sudo rm -rf /opt/ghc
           sudo rm -rf "/usr/local/share/boost"
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1.6.0
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        uses: docker/setup-buildx-action@v2.2.1
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
       - name: Set tag & see if it exists
         continue-on-error: true
         run: |
@@ -157,17 +159,17 @@ jobs:
           echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
           docker manifest inspect $DOCKER_TAG >/dev/null
           echo "not_yet_exists=$?" >> $GITHUB_OUTPUT
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
       - name: Prep Dockerfiles for forked repository
-        if: github.repository_owner != 'FCP-INDI' && contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        if: github.repository_owner != 'FCP-INDI' && contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
         run: |
             .github/scripts/local_ghcr .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile ${{ github.repository_owner }} $DOCKER_TAG
             cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
       - name: See Dockerfile
         run: cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
       - name: Build and push Docker image
-        uses: docker/build-push-action@v2.9.0
+        uses: docker/build-push-action@v3.2.0
         with:
           context: .
           file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
@@ -175,12 +177,14 @@ jobs:
           tags: |
             ${{ env.DOCKER_TAG }}
           cache-from: type=gha
-          cache-to: type=gha,mode=max
-        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile)
+          cache-to: type=gha,mode=min
+        if: contains(steps.changed-files-base.outputs.all_changed_files, matrix.Dockerfile) || contains(steps.changed-files.outputs.all_changed_files, matrix.Dockerfile) || (startsWith(matrix.Dockerfile, 'AFNI') && (contains(steps.changed-files.outputs.all_changed_files, 'dev/docker_data/required_afni_pkgs.txt')))
 
   build-base:
     needs: stages
     runs-on: ubuntu-latest
+    env:
+      BUILD_CACHE: /home/runner/.docker/buildkit
     strategy:
       matrix:
         variant:
@@ -206,9 +210,13 @@ jobs:
       with:
         fetch-depth: 2
     - name: Prep source files
-      run: sed -i -e 's/^/\.github\/Dockerfiles\//' .github/stage_requirements/${{ matrix.variant }}.txt
+      run: |
+          sed -i -e 's/^/\.github\/Dockerfiles\//' .github/stage_requirements/${{ matrix.variant }}.txt
+          echo 'dev/docker_data/required_afni_pkgs.txt' >> .github/stage_requirements/${{ matrix.variant }}.txt
+          echo '.github/workflows/build_stages.yml' >> .github/stage_requirements/${{ matrix.variant }}.txt
+          echo '.github/stage_requirements/${{ matrix.variant }}.txt' >> .github/stage_requirements/${{ matrix.variant }}.txt
     - name: Get changed files since fork point
-      uses: tj-actions/changed-files@v17.2
+      uses: tj-actions/changed-files@v34.0.0
       if: github.event.inputs.base_ref != ''
       id: changed-files-base
       with:
@@ -216,7 +224,7 @@ jobs:
         files_from_source_file: |
           .github/stage_requirements/${{ matrix.variant }}.txt
     - name: Get changed files since last commit
-      uses: tj-actions/changed-files@v17.2
+      uses: tj-actions/changed-files@v34.0.0
       if: github.event.inputs.base_ref == ''
       id: changed-files
       with:
@@ -240,7 +248,7 @@ jobs:
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
     - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1.6.0
+      uses: docker/setup-buildx-action@v2.2.1
       if: always() && steps.changed-files-base.outputs.any_changed == 'true' || steps.changed-files.outputs.any_changed == 'true' || steps.docker_tag.not_yet_exists == 1
     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v2
@@ -258,7 +266,7 @@ jobs:
       run: cat .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
       if: always() && steps.changed-files-base.outputs.any_changed == 'true' || steps.changed-files.outputs.any_changed == 'true' || steps.docker_tag.not_yet_exists == 1
     - name: Build and push base image
-      uses: docker/build-push-action@v2.9.0
+      uses: docker/build-push-action@v3.2.0
       with:
         context: .
         file: .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
@@ -266,7 +274,7 @@ jobs:
         tags: |
           ${{ env.DOCKER_TAG }}
         cache-from: type=gha
-        cache-to: type=gha,mode=max
+        cache-to: type=gha,mode=min
       if: always() && steps.changed-files-base.outputs.any_changed == 'true' || steps.changed-files.outputs.any_changed == 'true' || steps.docker_tag.not_yet_exists == 1
 
   trigger-next-workflow:
