:construction_worker: Shift bottleneck

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -16,26 +16,315 @@
 # License along with C-PAC. If not, see <https://www.gnu.org/licenses/>.
 name: Build and test C-PAC
 
+
 on:
   workflow_call:
+    inputs:
+      phase_one:
+        description: 'first phase of staging images to include (OS & data)'
+        type: string
+        required: true
+      rebuild_phase_one:
+        description: 'first phase of staging images to rebuild (OS & data)'
+        type: string
+        required: true
+      phase_two:
+        description: 'second phase of staging images to include (dependencies)'
+        type: string
+        required: true
+      rebuild_phase_two:
+        description: 'second phase of staging images to rebuild (dependencies)'
+        type: string
+        required: true
+      phase_three:
+        description: 'third phase of staging images to include (base images)'
+        type: string
+        required: true
+      rebuild_phase_three:
+        description: 'third phase of staging images to rebuild (base images)'
+        type: string
+        required: true
 
 jobs:
+  Ubuntu:
+    name: Build C-PAC stage images for Ubuntu & FSL data
+    strategy:
+      matrix:
+        Dockerfile: ${{ fromJSON(inputs.phase_one) }}
+    env:
+      REBUILD: ${{ inputs.rebuild_phase_one }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out C-PAC
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set tag & see if it exists
+        continue-on-error: true
+        id: docker_tag
+        if: always()
+        run: |
+          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
+          DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]')
+          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
+          docker buildx imagetools inspect $DOCKER_TAG >/dev/null || echo "not_yet_exists=1" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+      - name: Clear up some space on runner
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Set up Docker Buildx
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/setup-buildx-action@v2.2.1
+      - name: Log in to GitHub Container Registry
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build and push Docker image
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/build-push-action@v4.0.0
+        with:
+          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
+          push: true
+          tags: |
+            ${{ env.DOCKER_TAG }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=min,compression=zstd
+  
+  stages:
+    name: Build C-PAC Docker stage images for dependencies
+    needs: Ubuntu
+    strategy:
+      matrix:
+        Dockerfile: ${{ fromJSON(inputs.phase_two) }}
+    env:
+      REBUILD: ${{ inputs.rebuild_phase_two }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out C-PAC
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set tag & see if it exists
+        continue-on-error: true
+        id: docker_tag
+        run: |
+          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
+          DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]')
+          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
+          docker buildx imagetools inspect $DOCKER_TAG >/dev/null || echo "not_yet_exists=1" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+        if: always()
+      - name: Prep Dockerfiles for forked repository
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+            .github/scripts/local_ghcr .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile ${{ github.repository_owner }} $DOCKER_TAG
+            cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
+      - name: See Dockerfile
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
+      - name: Clear up some space on runner
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Set up Docker Buildx
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/setup-buildx-action@v2.2.1
+      - name: Log in to GitHub Container Registry
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build and push Docker image
+        if: contains(fromJSON(env.REBUILD), matrix.Dockerfile) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/build-push-action@v4.0.0
+        with:
+          context: .
+          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
+          push: true
+          tags: |
+            ${{ env.DOCKER_TAG }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=min,compression=zstd
+
+  build-base:
+    name: Build C-PAC base stage images
+    needs: stages
+    runs-on: ubuntu-latest
+    env:
+      BUILD_CACHE: /home/runner/.docker/buildkit
+      REBUILD: ${{ inputs.rebuild_phase_three }}
+    strategy:
+      matrix:
+        variant: ${{ fromJSON(inputs.phase_three) }}
+    steps:
+      - name: Maximize build space
+        uses: easimon/maximize-build-space@v6
+        with:
+          remove-dotnet: 'true'
+          remove-android: 'true'
+          remove-haskell: 'true'
+          overprovision-lvm: 'true'
+      - name: Check out C-PAC
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Prep source files
+        run: |
+            sed -i -e 's/^/\.github\/Dockerfiles\//' .github/stage_requirements/${{ matrix.variant }}.txt
+            echo 'dev/docker_data/required_afni_pkgs.txt' >> .github/stage_requirements/${{ matrix.variant }}.txt
+            echo '.github/workflows/build_and_test.yml' >> .github/stage_requirements/${{ matrix.variant }}.txt
+            echo '.github/stage_requirements/${{ matrix.variant }}.txt' >> .github/stage_requirements/${{ matrix.variant }}.txt
+      - name: Set tag & see if it exists
+        continue-on-error: true
+        run: |
+          TAG="stage-base:${{ matrix.variant }}-$(cat version)"
+          DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]')
+          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
+          docker buildx imagetools inspect $DOCKER_TAG >/dev/null || echo "not_yet_exists=1" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+        id: docker_tag
+        if: always()
+      - name: Prep Dockerfiles for forked repository
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+            .github/scripts/local_ghcr .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile ${{ github.repository_owner }} $DOCKER_TAG
+            cat .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
+      - name: See Dockerfile
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: cat .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
+      - name: Clear up some space on runner
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Set up Docker Buildx
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/setup-buildx-action@v2.2.1
+      - name: Log in to GitHub Container Registry
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build and push base image
+        if: contains(fromJSON(env.REBUILD), matrix.variant) || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/build-push-action@v4.0.0
+        with:
+          context: .
+          file: .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
+          provenance: false
+          sbom: false
+          push: true
+          tags: |
+            ${{ env.DOCKER_TAG }}
+
+  build-base-standard:
+    name: Build C-PAC standard base stage image
+    needs: build-base
+    runs-on: ubuntu-latest
+    env:
+      BUILD_CACHE: /home/runner/.docker/buildkit
+      REBUILD: ${{ inputs.rebuild_phase_three }}
+    steps:
+      - name: Maximize build space
+        uses: easimon/maximize-build-space@v6
+        with:
+          remove-dotnet: 'true'
+          remove-android: 'true'
+          remove-haskell: 'true'
+          overprovision-lvm: 'true'
+      - name: Check out C-PAC
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Prep source files
+        run: |
+            sed -i -e 's/^/\.github\/Dockerfiles\//' .github/stage_requirements/standard.txt
+            echo 'dev/docker_data/required_afni_pkgs.txt' >> .github/stage_requirements/standard.txt
+            echo '.github/workflows/build_and_test.yml' >> .github/stage_requirements/standard.txt
+            echo '.github/stage_requirements/standard.txt' >> .github/stage_requirements/standard.txt
+      - name: Set tag & see if it exists
+        continue-on-error: true
+        run: |
+          TAG="stage-base:standard-$(cat version)"
+          DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]')
+          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_ENV
+          docker buildx imagetools inspect $DOCKER_TAG >/dev/null || echo "not_yet_exists=1" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+        id: docker_tag
+        if: always()
+      - name: Prep Dockerfiles for forked repository
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+            .github/scripts/local_ghcr .github/Dockerfiles/base-standard.Dockerfile ${{ github.repository_owner }} $DOCKER_TAG
+            cat .github/Dockerfiles/base-standard.Dockerfile
+      - name: See Dockerfile
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        run: cat .github/Dockerfiles/base-standard.Dockerfile
+      - name: Clear up some space on runner
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Set up Docker Buildx
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/setup-buildx-action@v2.2.1
+      - name: Log in to GitHub Container Registry
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build and push base image
+        if: contains(fromJSON(env.REBUILD), 'standard') || steps.docker_tag.outputs.not_yet_exists == 1
+        uses: docker/build-push-action@v4.0.0
+        with:
+          context: .
+          file: .github/Dockerfiles/base-standard.Dockerfile
+          provenance: false
+          sbom: false
+          push: true
+          tags: |
+            ${{ env.DOCKER_TAG }}
+
   C-PAC:
+    needs: build-base-standard
     uses: ./.github/workflows/build_C-PAC.yml
     with:
       variant: ''
 
   C-PAC-lite:
+    needs: build-base
     uses: ./.github/workflows/build_C-PAC.yml
     with:
       variant: lite
 
   C-PAC-ABCD-HCP:
+    needs: build-base
     uses: ./.github/workflows/build_C-PAC.yml
     with:
       variant: ABCD-HCP
 
   C-PAC-fMRIPrep-LTS:
+    needs: build-base
     uses: ./.github/workflows/build_C-PAC.yml
     with:
       variant: fMRIPrep-LTS
